# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish package to the Maven Central Repository
on:
  #push:
    #branches: [ "main" ]
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version:  '17'
          distribution:  'temurin'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6
      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.OSSRHPASSWORD}}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.OSSRHUSERNAME}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.PGP_SECRET}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.PGP_PASSPHRASE}}
        run: ./gradlew publishToMavenCentral